version: '3'
services:
  api:
    build:
      context: ./server
  client:
    build:
      context: ./client
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'