version: '3'
services:
  api:
    build:
      context: ./server
    ports:
     - "3000:3000" #try to remove
  client:
    build:
      context: ./client
    ports:
      - "8082:8080" #try to remove
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'